-- AlterTable
ALTER TABLE "Game" ADD COLUMN     "awayQb" TEXT,
ADD COLUMN     "divGame" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "homeQb" TEXT,
ADD COLUMN     "spreadLine" DOUBLE PRECISION,
ADD COLUMN     "tempF" DOUBLE PRECISION,
ADD COLUMN     "totalLine" DOUBLE PRECISION,
ADD COLUMN     "windMph" DOUBLE PRECISION;
