/**
 * Cross-check the TypeScript edge maths against the Python it was ported from.
 *
 * The board now reprices against a live quote in TS, while the Python job remains
 * authoritative for what gets stored and graded. Two implementations of the same
 * formula is a liability unless something pins them together -- a fee rate corrected
 * in one and not the other would show the user a number that no grade will ever
 * match. Expected values below are generated from pipeline/model/signal.py.
 */
import { computeEdge, marginalFeeCents, pOverAtStrike } from "../src/lib/edge.ts";

let failures = 0;
const near = (a, b, tol = 1e-6) => Math.abs(a - b) <= tol;

function check(name, got, want, tol) {
  const ok = typeof want === "number" ? near(got, want, tol) : got === want;
  if (!ok) {
    failures++;
    console.error(`  FAIL ${name}: got ${got}, want ${want}`);
  }
  return ok;
}

// Generated by pipeline/model/signal.py -- do not hand-edit.
const GOLDEN = [
  { pOver: 0.62, ask: 0.5,  side: "yes", modelProb: 0.62, marketProb: 0.5,  feeCents: 1.75,   net: 10.25,    kelly: 0.24 },
  { pOver: 0.3,  ask: 0.55, side: "no",  modelProb: 0.7,  marketProb: 0.45, feeCents: 1.7325, net: 23.2675,  kelly: 0.454545 },
  { pOver: 0.55, ask: 0.54, side: "yes", modelProb: 0.55, marketProb: 0.54, feeCents: 1.7388, net: -0.7388,  kelly: 0.021739 },
  { pOver: 0.9,  ask: 0.1,  side: "yes", modelProb: 0.9,  marketProb: 0.1,  feeCents: 0.63,   net: 79.37,    kelly: 0.888889 },
  { pOver: 0.05, ask: 0.9,  side: "no",  modelProb: 0.95, marketProb: 0.1,  feeCents: 0.63,   net: 84.37,    kelly: 0.944444 },
  { pOver: 0.5,  ask: 0.5,  side: "yes", modelProb: 0.5,  marketProb: 0.5,  feeCents: 1.75,   net: -1.75,    kelly: 0.0 },
];

console.log("edge maths vs Python golden values");
for (const g of GOLDEN) {
  const e = computeEdge(g.pOver, g.ask);
  const label = `p=${g.pOver} ask=${g.ask}`;
  check(`${label} side`, e.side, g.side);
  check(`${label} modelProb`, e.modelProb, g.modelProb);
  check(`${label} marketProb`, e.marketProb, g.marketProb);
  check(`${label} fee`, e.feeCents, g.feeCents);
  check(`${label} net`, e.edgeCentsNet, g.net, 1e-4);
  check(`${label} kelly`, e.kelly, g.kelly, 1e-5);
}

console.log("fee rate at the extremes");
check("fee(0.5)", marginalFeeCents(0.5), 1.75);
check("fee(0.25)", marginalFeeCents(0.25), 1.3125);
check("fee(0.1)", marginalFeeCents(0.1), 0.63);

console.log("side can flip when the price moves");
// Same model number, two prices: the stored side is not necessarily still right.
check("cheap over -> yes", computeEdge(0.6, 0.40).side, "yes");
check("expensive over -> no", computeEdge(0.6, 0.85).side, "no");

console.log("a strike with no stored probability yields null, never a guess");
check("missing strike", pOverAtStrike({ "250": 0.6 }, 275), null);
check("present strike", pOverAtStrike({ "250": 0.6 }, 250), 0.6);
check("float-formatted strike", pOverAtStrike({ "250.0": 0.6 }, 250), 0.6);
check("null strike", pOverAtStrike({ "250": 0.6 }, null), null);
check("out-of-range value rejected", pOverAtStrike({ "250": 1.4 }, 250), null);

if (failures) {
  console.error(`\n${failures} check(s) failed`);
  process.exit(1);
}
console.log("\nall checks passed");
